name: CI to Docker Hub

on:
  push:
    branches: 
      - master
      - dev
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: docker build
        run: docker build . --file Dockerfile --tag public.ecr.aws/q5y5m4j7/flask-app/dev:${GITHUB_RUN_NUMBER}
        
      - name: docker push
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q5y5m4j7
          docker push public.ecr.aws/q5y5m4j7/flask-app/dev:${GITHUB_RUN_NUMBER}
